# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='pro_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Province', verbose_name='城市所在省份'),
        ),
    ]
