# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ill_name', models.CharField(max_length=100, verbose_name='疾病名称')),
                ('symptom', models.CharField(max_length=255, verbose_name='症状')),
                ('pathogeny', models.CharField(max_length=255, verbose_name='病因')),
                ('treatment', models.CharField(max_length=255, verbose_name='治疗')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='诊断')),
                ('Prevention', models.CharField(max_length=255, verbose_name='预防')),
                ('life', models.CharField(max_length=255, verbose_name='生活')),
            ],
            options={
                'verbose_name': '疾病表',
                'verbose_name_plural': '疾病表',
                'db_table': 'yl_diseases',
            },
        ),
    ]
