# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.FloatField(verbose_name='药品价格'),
        ),
    ]
