# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('auth', models.CharField(max_length=20, verbose_name='文章作者')),
                ('subjection', models.CharField(max_length=100, verbose_name='作者所属平台')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '科普文章',
                'verbose_name_plural': '科普文章',
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Collect_art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'collect_art',
            },
        ),
    ]
