# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arti_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=100, verbose_name='常见疾病类别')),
            ],
            options={
                'verbose_name': '科普分类',
                'verbose_name_plural': '科普分类',
                'db_table': 'art_title',
            },
        ),
        migrations.CreateModel(
            name='Article_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200, verbose_name='科普文章图片')),
                ('subtitle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Arti_title', verbose_name='常见疾病')),
            ],
            options={
                'verbose_name': '科普常见疾病',
                'verbose_name_plural': '科普常见疾病',
                'db_table': 'article_image',
            },
        ),
    ]
