# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_auth_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_img',
            field=models.CharField(max_length=200, null=True, verbose_name='文章图片'),
        ),
    ]
