# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_image_art_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='art_class',
            field=models.CharField(max_length=50, null=True, verbose_name='文章分类'),
        ),
    ]
