# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_auto_20190701_1831'),
        ('medicine', '0002_auto_20190702_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_med_num', models.IntegerField(verbose_name='下单数量')),
                ('c_is_select', models.BooleanField(default=False, verbose_name='选中状态')),
                ('c_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.Medicine', verbose_name='药品')),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'db_table': 'carts',
            },
        ),
    ]
