# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190703_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='o_addr',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='o_consignee',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='o_phone',
        ),
        migrations.AddField(
            model_name='order',
            name='o_addr',
            field=models.CharField(max_length=200, null=True, verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='o_consignee',
            field=models.CharField(max_length=20, null=True, verbose_name='收货人'),
        ),
        migrations.AddField(
            model_name='order',
            name='o_phone',
            field=models.CharField(max_length=15, null=True, verbose_name='收货人手机号'),
        ),
    ]
