# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190701_1831'),
        ('order', '0003_auto_20190703_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=20, verbose_name='收货人')),
                ('r_phone', models.CharField(max_length=15, verbose_name='收货人电话')),
                ('r_addr', models.CharField(max_length=200, verbose_name='收货地址')),
                ('r_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '收货信息',
                'verbose_name_plural': '收货信息',
                'db_table': 'yl_receive',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='o_addr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='o_consignee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='o_phone',
        ),
        migrations.AddField(
            model_name='order',
            name='o_receive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Receive', verbose_name='收货人信息'),
            preserve_default=False,
        ),
    ]
