# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190703_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='r_default',
            field=models.BooleanField(default=False, verbose_name='默认收货地址'),
        ),
    ]
