# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_receive_r_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_receive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Receive', verbose_name='收货人信息'),
        ),
    ]
