# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190704_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='o_med_num',
            field=models.IntegerField(null=True, verbose_name='药品数量'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='o_med_price',
            field=models.FloatField(null=True, verbose_name='单个药品总价'),
        ),
    ]
