# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20, verbose_name='患者姓名')),
                ('p_ID_number', models.CharField(max_length=18, verbose_name='身份证号')),
                ('p_sex', models.CharField(default='男', max_length=2, verbose_name='性别')),
                ('date_birth', models.DateTimeField(verbose_name='出生年月')),
                ('p_weight', models.CharField(max_length=10, verbose_name='体重')),
                ('is_allergy', models.BooleanField(default=False, verbose_name='过敏史')),
                ('medical_history', models.CharField(blank=True, max_length=100, null=True, verbose_name='过敏病史')),
                ('is_normal_liver', models.BooleanField(default=True, verbose_name='肝功')),
                ('is_normal_kidney', models.BooleanField(default=True, verbose_name='肾功')),
                ('is_pregnancy_preparation', models.BooleanField(default=False, verbose_name='是否备孕')),
            ],
            options={
                'verbose_name': '患者表',
                'verbose_name_plural': '患者表',
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_auth_str', models.CharField(max_length=200, verbose_name='口令')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
                ('nice_name', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('sex', models.CharField(max_length=2)),
                ('photo', models.CharField(default='\n    http://img2.imgtn.bdimg.com/it/u=1813493607,361824557&fm=26&gp=0.jpg\n    ', max_length=255, verbose_name='头像')),
                ('activated', models.IntegerField(default=1, verbose_name=1)),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'yl_user',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='p_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户名称'),
        ),
    ]
