# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190701_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(max_length=700, null=True, verbose_name='头像'),
        ),
    ]
