# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorquality',
            name='dis_num',
            field=models.IntegerField(null=True, verbose_name='折扣剩余名额'),
        ),
        migrations.AddField(
            model_name='doctorquality',
            name='discount',
            field=models.CharField(max_length=50, null=True, verbose_name='是否折扣'),
        ),
        migrations.AddField(
            model_name='doctorquality',
            name='new_excl',
            field=models.CharField(max_length=50, null=True, verbose_name='新人专享'),
        ),
    ]
