# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20190701_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorquality',
            name='new_excl',
            field=models.BooleanField(default=1, verbose_name='是否新人专享'),
            preserve_default=False,
        ),
    ]
