# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20190701_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focus_doc',
            old_name='arc',
            new_name='doc',
        ),
    ]
